name: tsdr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.8
  # Backend
  - django==3.2.5
  - django-ninja==0.17.0
  - uvicorn==0.18.3
  # Pytorch
  - pytorch==1.12.1
  - torchvision==0.13.1
  - cudatoolkit==11.3.1
  # Tsr Resnet
  - pandas==1.5.0
  - matplotlib==3.6.0
  - imgaug==0.4.0
  - albumentations==1.3.0
  # Tsd yolox
  # - ninja==1.11.0 -> Conflicts with django-ninja, not needed for inference, only for training
  - tensorboard==2.10.0
  - pillow==9.2.0
  - tabulate==0.8.10
  - scikit-image==0.19.3
  - loguru==0.6.0
  # General
  # - opencv
  - tqdm==4.64.1
  - cudnn==8.2.1
  # Pip
  - pip==22.3
  - pip:
    # General
    # - opencv-python
    # Backend
    - aiortc==1.3.2
    # Tsd yolox
    - thop==0.1.1.post2209072238
    # Replace with pycocotools on linux
    - pycocotools-windows==2.0.0.2
    - onnx==1.8.1
    - onnxruntime==1.8.0
    - onnx-simplifier==0.3.5